#!/usr/bin/env python
import sys
import base.project as project
from base.utils import PtpException
from gencpp.generator import CppProgramGenerator, CppLibGenerator
import traceback
import argparse

debug_mode = False

generators = {
    "C++" : CppProgramGenerator,
    "C++ library" : CppLibGenerator
}

def get_generator(project):
    g = generators.get(project.get_extenv())
    if g is None:
        raise PtpException("Unknown extenv '{0}'".format(project.get_extenv()))
    else:
        return g(project)

def get_generator_from_xml(element):
    return get_generator(project.load_project(element))

def main():
    parser = argparse.ArgumentParser(description="PTP - ProjectToProgram compiler")
    parser.add_argument("operation",
                        metavar="OPERATION",
                        type=str,
                        help="Possible values: build, statespace,"
                             "place-user-fn, transition-user-fn")
    parser.add_argument("project",
                        metavar="FILENAME",
                        type=str,
                        help="path to XML file generated by GUI")
    parser.add_argument("--debug",
                        action='store_true',
                        help="Run PTP in debug mode")
    parser.add_argument("--output",
                        metavar="DIRECTORY",
                        type=str,
                        help="Directory where output files are generated")
    args = parser.parse_args()

    if args.debug:
        global debug_mode
        debug_mode = True

    p = project.load_project_from_file(args.project)
    generator = get_generator(p)

    if args.output is None:
        output_directory = "."
    else:
        output_directory = args.output

    if args.operation == "build":
        generator.build(output_directory)
    elif args.operation == "statespace":
        generator.build_statespace(output_directory)
    else:
        raise PtpException("Unknown operation")

if __name__ == '__main__':
    try:
        main()
    except PtpException, e:
        print e
        if debug_mode:
            traceback.print_exc(file=sys.stdout)
        sys.exit(1)
